# OSx2 (RTECH dos) Root Makefile - Professional Edition

CC = gcc
LD = ld
OBJCOPY = objcopy

# Load Configuration (Generated by make menuconfig)
-include .config

# Set defaults if not configured
CONFIG_KERNEL_BASE ?= 0x1000000
CONFIG_HEAP_BASE   ?= 0x2000000
CONFIG_OPTIMIZATION ?= 0

# Paths
BOOT_DIR = boot
EFI_DIR = $(BOOT_DIR)/EFI/BOOT
LOADER_DIR = loader
KERNEL_DIR = kernel/unice64
LIBS_DIR = kernel/libs

# GNU-EFI Paths
EFI_LIB = /usr/lib
EFI_LDS = /usr/lib/elf_x86_64_efi.lds
EFI_CRT0 = /usr/lib/crt0-efi-x86_64.o

# Flags
CFLAGS_COMMON = -Iinclude -fno-stack-protector -mno-red-zone -Wall -fno-builtin -m64 -O$(CONFIG_OPTIMIZATION)
CFLAGS_EFI = $(CFLAGS_COMMON) -fpic -fshort-wchar -DEFI_FUNCTION_WRAPPER -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol
CFLAGS_KERNEL = $(CFLAGS_COMMON) -I$(LIBS_DIR) -I$(LIBS_DIR)/core -I$(KERNEL_DIR) -ffreestanding -mcmodel=large -fno-stack-protector -fno-pic -fno-pie -fno-plt

LDFLAGS_EFI = -nostdlib -znocombreloc -T $(EFI_LDS) -shared -Bsymbolic -L $(EFI_LIB) $(EFI_CRT0)
LDFLAGS_KERNEL = -nostdlib -T $(BOOT_DIR)/linker.ld --oformat binary --defsym=KERNEL_BASE=$(CONFIG_KERNEL_BASE)
LDFLAGS_SHELL = -nostdlib -T programs/linker.ld --oformat binary

LIBS_EFI = -lefi -lgnuefi

# Source Files
LOADER_OBJS = $(LOADER_DIR)/entry.o $(LOADER_DIR)/panic.o

# ORDER MATTERS: main.o must be first for raw binary entry
KERNEL_OBJS = $(KERNEL_DIR)/entry.o \
              $(KERNEL_DIR)/main.o \
              $(KERNEL_DIR)/gdt.o \
              $(LIBS_DIR)/kutils.o \
              $(LIBS_DIR)/console.o \
              $(LIBS_DIR)/font_data.o \
              $(LIBS_DIR)/input.o \
              $(LIBS_DIR)/connect.o \
              $(LIBS_DIR)/vdisk.o \
              $(LIBS_DIR)/disk.o \
              $(LIBS_DIR)/diskman.o \
              $(LIBS_DIR)/memory.o \
              $(LIBS_DIR)/fs.o \
              $(LIBS_DIR)/rnafs.o \
              $(LIBS_DIR)/loader.o \
              $(LIBS_DIR)/core/event.o

SHELL_SRCS = programs/libsystem.c programs/shell.c
SHELL_OBJS = $(SHELL_SRCS:.c=.o)

HEADERS = $(shell find include kernel loader -name "*.h")

# Default Target
all: info prepare $(EFI_DIR)/BOOTX64.EFI $(BOOT_DIR)/os2.bin $(BOOT_DIR)/shell.bin

info:
	@echo "------------------------------------------------"
	@echo " OSx2 / RTECH dos Build System"
	@echo " Kernel Base: $(CONFIG_KERNEL_BASE)"
	@echo " Heap Base:   $(CONFIG_HEAP_BASE)"
	@echo " Optimization Level: -O$(CONFIG_OPTIMIZATION)"
	@echo "------------------------------------------------"

prepare:
	@if [ ! -f .config ]; then \
		echo "No .config found, generating defaults..."; \
		python3 scripts/menuconfig.py --save; \
	fi

menuconfig:
	@python3 scripts/menuconfig.py

# Stage 1: Loader (EFI)
$(EFI_DIR)/BOOTX64.EFI: loader.so
	@mkdir -p $(EFI_DIR)
	$(OBJCOPY) -j .text -j .sdata -j .data -j .dynamic \
	           -j .dynsym  -j .rel -j .rela -j .reloc \
	           -j .rodata* --target=efi-app-x86_64 loader.so $(EFI_DIR)/BOOTX64.EFI

loader.so: $(LOADER_OBJS)
	$(LD) $(LDFLAGS_EFI) $(LOADER_OBJS) -o loader.so $(LIBS_EFI)

$(LOADER_DIR)/%.o: $(LOADER_DIR)/%.c $(HEADERS)
	$(CC) $(CFLAGS_EFI) -c $< -o $@

$(LOADER_DIR)/%.o: $(LOADER_DIR)/%.asm
	nasm -f elf64 $< -o $@

# Stage 2: Kernel (Raw Binary)
$(BOOT_DIR)/os2.bin: $(KERNEL_OBJS)
	$(LD) $(LDFLAGS_KERNEL) $(KERNEL_OBJS) -o $(BOOT_DIR)/os2.bin

$(KERNEL_DIR)/%.o: $(KERNEL_DIR)/%.c $(HEADERS)
	$(CC) $(CFLAGS_KERNEL) -c $< -o $@

$(KERNEL_DIR)/%.o: $(KERNEL_DIR)/%.asm
	nasm -f elf64 $< -o $@

$(LIBS_DIR)/%.o: $(LIBS_DIR)/%.c $(HEADERS)
	$(CC) $(CFLAGS_KERNEL) -c $< -o $@

$(LIBS_DIR)/core/%.o: $(LIBS_DIR)/core/%.c $(HEADERS)
	$(CC) $(CFLAGS_KERNEL) -c $< -o $@

# Programs
$(BOOT_DIR)/shell.bin: $(SHELL_OBJS)
	$(LD) $(LDFLAGS_SHELL) $(SHELL_OBJS) -o $(BOOT_DIR)/shell.bin

programs/%.o: programs/%.c $(HEADERS)
	$(CC) $(CFLAGS_KERNEL) -c $< -o $@

# Advanced Tools: Create Bootable UEFI Disk Image
disk: all
	@echo "Creating bootable UEFI disk image..."
	dd if=/dev/zero of=disk.img bs=1M count=64
	mformat -i disk.img -F -v "OSX2" ::
	mmd -i disk.img ::/EFI
	mmd -i disk.img ::/EFI/BOOT
	mcopy -i disk.img $(EFI_DIR)/BOOTX64.EFI ::/EFI/BOOT/BOOTX64.EFI
	mcopy -i disk.img $(BOOT_DIR)/os2.bin ::/os2.bin
	mcopy -i disk.img $(BOOT_DIR)/shell.bin ::/shell.bin
	@echo "OSx2 Pro UEFI Disk Image Ready (disk.img)."

iso: disk
	mkdir -p iso_root/EFI/BOOT
	cp $(EFI_DIR)/BOOTX64.EFI iso_root/EFI/BOOT/
	cp $(BOOT_DIR)/os2.bin iso_root/
	cp $(BOOT_DIR)/shell.bin iso_root/
	xorriso -as mkisofs -R -f -e disk.img -no-emul-boot -o boot.iso iso_root
	rm -rf iso_root

# Advanced Tools: Create Bootable UEFI Disk Image
run: disk
	qemu-system-x86_64 -bios /usr/share/ovmf/OVMF.fd -drive format=raw,file=disk.img -m 256M -serial stdio

setup:
	sudo apt-get update
	sudo apt-get install -y gnu-efi build-essential qemu-system-x86 ovmf mtools dosfstools

update: clean all
	@echo "OSx2 System Update Complete."

# Cleanup
clean:
	@find . -name "*.o" -delete
	@rm -f loader.so $(BOOT_DIR)/os2.bin $(BOOT_DIR)/shell.bin disk.img
	@rm -rf $(BOOT_DIR)/EFI
	@echo "Build artifacts removed."

.PHONY: all clean disk prepare menuconfig info update
