import curses
import os
import sys

# OSx2 Configuration Options - Professional Suite
OPTIONS = [
    {"id": "CONFIG_DEBUG_LOGS", "label": "Enable Debug Logging", "type": "bool", "default": True},
    {"id": "CONFIG_KERNEL_BASE", "label": "Kernel Base Address (Hex)", "type": "hex", "default": 0x1000000},
    {"id": "CONFIG_HEAP_BASE", "label": "ARC Heap Base Address (Hex)", "type": "hex", "default": 0x2000000},
    {"id": "CONFIG_HEAP_SIZE_MB", "label": "Global Heap Size (MB)", "type": "int", "default": 8},
    {"id": "CONFIG_SCROLL_SPEED", "label": "Console Scroll Speed (Pixels)", "type": "int", "default": 10},
    {"id": "CONFIG_EMERALD_MODE", "label": "Enable High-Contrast Emerald Theme", "type": "bool", "default": True},
    {"id": "CONFIG_FG_COLOR", "label": "Default FG Color (RGB Hex)", "type": "hex", "default": 0x00FF88},
    {"id": "CONFIG_BG_COLOR", "label": "Default BG Color (RGB Hex)", "type": "hex", "default": 0x000000},
    {"id": "CONFIG_LOAD_SHELL", "label": "Auto-load shell.bin on boot", "type": "bool", "default": True},
    {"id": "CONFIG_OPTIMIZATION", "label": "Compiler Optimization (-O0, -O1, -O2)", "type": "int", "default": 0},
    {"id": "CONFIG_STRICT_CHECKS", "label": "Enable Strict Memory Bounds Checking", "type": "bool", "default": True},
]

class MenuConfig:
    def __init__(self, stdscr):
        self.stdscr = stdscr
        self.cursor = 0
        self.values = {}
        self.load_config()

    def load_config(self):
        if os.path.exists(".config"):
            with open(".config", "r") as f:
                for line in f:
                    if "=" in line:
                        parts = line.strip().split("=")
                        if len(parts) == 2:
                            k, v = parts
                            if v == "y": self.values[k] = True
                            elif v == "n": self.values[k] = False
                            elif v.startswith("0x"): self.values[k] = int(v, 16)
                            elif v.isdigit(): self.values[k] = int(v)
                            else: self.values[k] = v

        for opt in OPTIONS:
            if opt["id"] not in self.values:
                self.values[opt["id"]] = opt["default"]

    def save_config(self):
        # Save .config for Makefile
        with open(".config", "w") as f:
            for k, v in self.values.items():
                if isinstance(v, bool):
                    f.write(f"{k}={'y' if v else 'n'}\n")
                elif isinstance(v, int):
                    # Check if it was originally hex
                    is_hex = False
                    for opt in OPTIONS:
                        if opt["id"] == k and opt["type"] == "hex":
                            is_hex = True
                            break
                    if is_hex: f.write(f"{k}={hex(v)}\n")
                    else: f.write(f"{k}={v}\n")
                else:
                    f.write(f"{k}={v}\n")

        # Save include/config.h for C
        with open("include/config.h", "w") as f:
            f.write("#ifndef CONFIG_H\n#define CONFIG_H\n\n")
            f.write("/* Auto-generated by OSx2 menuconfig Professional */\n\n")
            for k, v in self.values.items():
                if isinstance(v, bool):
                    if v: f.write(f"#define {k} 1\n")
                    else: f.write(f"/* #undef {k} */\n")
                elif isinstance(v, int):
                    f.write(f"#define {k} {hex(v) if v > 1000 else v}\n")
                else:
                    f.write(f"#define {k} {v}\n")
            f.write("\n#endif\n")

    def run(self):
        curses.curs_set(0)
        self.stdscr.nodelay(0)
        self.stdscr.keypad(True)

        while True:
            self.stdscr.clear()
            h, w = self.stdscr.getmaxyx()

            # Draw header
            self.stdscr.attron(curses.A_REVERSE)
            self.stdscr.addstr(0, 0, " OSx2 / RTECH dos Advanced Configuration Utility ".center(w))
            self.stdscr.attroff(curses.A_REVERSE)

            # Draw options
            for i, opt in enumerate(OPTIONS):
                val = self.values[opt["id"]]
                if isinstance(val, bool):
                    prefix = "[*]" if val else "[ ]"
                elif i == self.cursor:
                    prefix = f"({hex(val) if isinstance(val, int) and val > 1000 else val})"
                else:
                    prefix = f" {hex(val) if isinstance(val, int) and val > 1000 else val} "

                label = f"{prefix.ljust(12)} {opt['label']}"

                if i == self.cursor:
                    self.stdscr.attron(curses.A_BOLD | curses.A_REVERSE)
                    self.stdscr.addstr(i + 2, 2, f" > {label} ")
                    self.stdscr.attroff(curses.A_BOLD | curses.A_REVERSE)
                else:
                    self.stdscr.addstr(i + 2, 2, f"   {label}")

            # Draw footer
            self.stdscr.addstr(h - 3, 2, "-" * (w - 4))
            self.stdscr.addstr(h - 2, 2, "Space/Enter: Edit | S: Save & Exit | Q: Discard & Quit")

            key = self.stdscr.getch()
            if key == ord('q'): break
            if key == ord('s'):
                self.save_config()
                break
            elif key == curses.KEY_UP:
                self.cursor = (self.cursor - 1) % len(OPTIONS)
            elif key == curses.KEY_DOWN:
                self.cursor = (self.cursor + 1) % len(OPTIONS)
            elif key in [ord(' '), 10, 13]:
                opt = OPTIONS[self.cursor]
                if opt["type"] == "bool":
                    self.values[opt["id"]] = not self.values[opt["id"]]
                else:
                    curses.echo()
                    self.stdscr.addstr(h - 1, 2, f"Set {opt['id']}: ".ljust(w-4))
                    self.stdscr.move(h - 1, len(opt['id']) + 7)
                    new_val = self.stdscr.getstr().decode()
                    curses.noecho()
                    try:
                        if opt["type"] == "hex":
                            if new_val.startswith("0x"): self.values[opt["id"]] = int(new_val, 16)
                            else: self.values[opt["id"]] = int(new_val, 16)
                        elif opt["type"] == "int":
                            self.values[opt["id"]] = int(new_val)
                    except:
                        pass

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--save":
        mc = MenuConfig(None)
        mc.save_config()
    else:
        curses.wrapper(lambda s: MenuConfig(s).run())
