import curses
import os

# OSx2 Configuration Options
OPTIONS = [
    {"id": "CONFIG_DEBUG_LOGS", "label": "Enable Debug Logging", "type": "bool", "default": True},
    {"id": "CONFIG_HEAP_SIZE_MB", "label": "Global Heap Size (MB)", "type": "int", "default": 4},
    {"id": "CONFIG_SCROLL_SPEED", "label": "Console Scroll Speed", "type": "int", "default": 10},
    {"id": "CONFIG_EMERALD_MODE", "label": "Force Emerald Green Theme", "type": "bool", "default": True},
    {"id": "CONFIG_LOAD_SHELL", "label": "Auto-load shell.bin on boot", "type": "bool", "default": True},
]

class MenuConfig:
    def __init__(self, stdscr):
        self.stdscr = stdscr
        self.cursor = 0
        self.values = {}
        self.load_config()

    def load_config(self):
        if os.path.exists(".config"):
            with open(".config", "r") as f:
                for line in f:
                    if "=" in line:
                        k, v = line.strip().split("=")
                        if v == "y": self.values[k] = True
                        elif v == "n": self.values[k] = False
                        else: self.values[k] = v

        for opt in OPTIONS:
            if opt["id"] not in self.values:
                self.values[opt["id"]] = opt["default"]

    def save_config(self):
        # Save .config for Makefile
        with open(".config", "w") as f:
            for k, v in self.values.items():
                if isinstance(v, bool):
                    f.write(f"{k}={'y' if v else 'n'}\n")
                else:
                    f.write(f"{k}={v}\n")

        # Save include/config.h for C
        with open("include/config.h", "w") as f:
            f.write("#ifndef CONFIG_H\n#define CONFIG_H\n\n")
            f.write("/* Auto-generated by OSx2 menuconfig */\n\n")
            for k, v in self.values.items():
                if isinstance(v, bool):
                    if v: f.write(f"#define {k} 1\n")
                    else: f.write(f"/* #undef {k} */\n")
                else:
                    f.write(f"#define {k} {v}\n")
            f.write("\n#endif\n")

    def run(self):
        curses.curs_set(0)
        self.stdscr.nodelay(0)
        self.stdscr.keypad(True)

        while True:
            self.stdscr.clear()
            h, w = self.stdscr.getmaxyx()

            # Draw header
            self.stdscr.attron(curses.A_REVERSE)
            self.stdscr.addstr(0, 0, " OSx2 / RTECH dos Configuration Utility ".center(w))
            self.stdscr.attroff(curses.A_REVERSE)

            # Draw options
            for i, opt in enumerate(OPTIONS):
                val = self.values[opt["id"]]
                prefix = "[*]" if val is True else "[ ]" if val is False else f"({val})"
                label = f"{prefix} {opt['label']}"

                if i == self.cursor:
                    self.stdscr.attron(curses.A_BOLD | curses.A_UNDERLINE)
                    self.stdscr.addstr(i + 2, 2, f"-> {label}")
                    self.stdscr.attroff(curses.A_BOLD | curses.A_UNDERLINE)
                else:
                    self.stdscr.addstr(i + 2, 2, f"   {label}")

            # Draw footer
            self.stdscr.addstr(h - 2, 2, "Space: Toggle/Edit | S: Save | Q: Quit")

            key = self.stdscr.getch()
            if key == ord('q'): break
            if key == ord('s'):
                self.save_config()
                self.stdscr.addstr(h - 1, 2, "Configuration saved!")
                self.stdscr.refresh()
                curses.napms(500)
            elif key == curses.KEY_UP:
                self.cursor = (self.cursor - 1) % len(OPTIONS)
            elif key == curses.KEY_DOWN:
                self.cursor = (self.cursor + 1) % len(OPTIONS)
            elif key == ord(' '):
                opt = OPTIONS[self.cursor]
                if opt["type"] == "bool":
                    self.values[opt["id"]] = not self.values[opt["id"]]
                elif opt["type"] == "int":
                    # Simple integer input
                    self.stdscr.addstr(h - 1, 2, f"Enter value for {opt['id']}: ")
                    curses.echo()
                    new_val = self.stdscr.getstr().decode()
                    curses.noecho()
                    if new_val.isdigit():
                        self.values[opt["id"]] = int(new_val)

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--save":
        # Headless save
        mc = MenuConfig(None)
        mc.save_config()
    else:
        curses.wrapper(lambda s: MenuConfig(s).run())
