import os
import sys

CONFIG_FILE = ".config"
HEADER_FILE = "include/config.h"

# Sections and their respective options with defaults
menu_structure = {
    "CORE SYSTEM": {
        "CONFIG_MEMORY_MB": "512",
        "CONFIG_SERIAL_DEBUG": "y",
    },
    "HARDWARE DRIVERS": {
        "CONFIG_USB_SUPPORT": "y",
        "CONFIG_PCI_ENUM": "y",
        "CONFIG_PS2_KEYBOARD": "y",
    },
    "FILESYSTEMS": {
        "CONFIG_RNAFS": "y",
        "CONFIG_FAT16": "y",
    },
    "POWER MANAGEMENT": {
        "CONFIG_POWER_SERVICES": "y",
        "CONFIG_PROMPTED_POWER": "y",
    },
    "USER INTERFACE": {
        "CONFIG_SHELL_AUTOSTART": "y",
    }
}

def load_config():
    # Flatten structure for easy access
    config = {}
    for section in menu_structure:
        for key, val in menu_structure[section].items():
            config[key] = val

    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "r") as f:
            for line in f:
                if "=" in line:
                    key, val = line.strip().split("=")
                    if key in config:
                        config[key] = val
    return config

def save_config(config):
    with open(CONFIG_FILE, "w") as f:
        for key, val in config.items():
            f.write(f"{key}={val}\n")

    with open(HEADER_FILE, "w") as f:
        f.write("#ifndef CONFIG_H\n#define CONFIG_H\n\n")
        f.write("/* Automatically generated by menuconfig.py */\n\n")
        for key, val in config.items():
            if val == "y":
                f.write(f"#define {key} 1\n")
            elif val == "n":
                f.write(f"#undef {key}\n")
            else:
                f.write(f"#define {key} {val}\n")
        f.write("\n#endif\n")

def main():
    config = load_config()

    if "--default" in sys.argv:
        if not os.path.exists(CONFIG_FILE) or not os.path.exists(HEADER_FILE):
            save_config(config)
        return

    while True:
        os.system('clear' if os.name == 'posix' else 'cls')
        print("--- OSx2 (RTECH dos) Configuration Menu ---")
        print("-------------------------------------------")

        all_options = []
        option_idx = 1

        for section in menu_structure:
            print(f"\n[{section}]")
            for key in menu_structure[section]:
                print(f"  {option_idx}. {key.replace('CONFIG_', '')}: {config[key]}")
                all_options.append(key)
                option_idx += 1

        print("\n-------------------------------------------")
        print("s. Save and Exit")
        print("q. Quit without saving")

        choice = input("\nSelect an option to toggle or change: ").strip().lower()

        if choice == 's':
            save_config(config)
            print("Configuration saved to .config and include/config.h")
            break
        elif choice == 'q':
            print("Exit without saving.")
            break

        try:
            idx = int(choice) - 1
            if 0 <= idx < len(all_options):
                key = all_options[idx]
                if config[key] in ["y", "n"]:
                    config[key] = "n" if config[key] == "y" else "y"
                else:
                    new_val = input(f"Enter new value for {key} (current: {config[key]}): ").strip()
                    if new_val:
                        config[key] = new_val
        except ValueError:
            pass

if __name__ == "__main__":
    main()
